server:
  port: 8888
resilience4j.bulkhead:
  instances:
    queryServerBulkhead:
      max-concurrent-calls: 10
      max-wait-duration: 0
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    enable:
      all: true
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: queryToDefaultPort
          uri: lb://query-server
          predicates:
            - Path=/query/**
          filters:
            - AddRequestHeader=Authorization,Basic YWRtaW46YWRtaW4=
            - Bulkhead


